version: '3.1'
services:
  dairo-music-search:
    image: dairopapa/dairo-music-search:1.0.2
    #    build: .
    restart: always
    container_name: dairo-music-search
    network_mode: host

    environment:
      #时区,解决时间不一致的bug
      TZ: Asia/Shanghai

      #解决控制台输出中文乱码
      LANG: C.UTF-8

      #谷歌开发者KEY
      GOOGLE_API_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      #临时文件路径
      CACHE_FOLDER: "./temp"
      #允许同时下载线程数
      MAX_DOWNLOAD_THREAD_COUNT: 1
      #WEB端口
      WEB_PORT: 8021
